plugins {
	id 'java'
	id 'war'
	id 'org.springframework.boot' version '3.5.15'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.liverpool'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
	maven { url 'https://repo.spring.io/snapshot' }
}

ext {
	springdocVersion = '2.8.8'
	mapstructVersion = '1.6.3'
	lombokVersion = '1.18.38'
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0'
	implementation "io.swagger.core.v3:swagger-annotations:2.2.15"
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'

	implementation 'com.fasterxml.jackson.core:jackson-databind'
	implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310'
	implementation 'org.springframework.boot:spring-boot-starter-validation'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.mockito:mockito-core:5.4.0'
	testImplementation 'org.mockito:mockito-junit-jupiter:5.4.0'

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	implementation "org.mapstruct:mapstruct:1.6.3"
	annotationProcessor "org.mapstruct:mapstruct-processor:1.6.3"
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

	//implementation("org.springframework.boot:spring-boot-starter-zipkin:4.1.0-M4")

	implementation "org.springframework.boot:spring-boot-starter-data-elasticsearch"
	//implementation "org.springframework.data:spring-data-elasticsearch"

	//implementation("org.springframework.boot:spring-boot-starter-data-elasticsearch:4.1.0")
}

tasks.named('test') {
	useJUnitPlatform()
}
